title: Your awesome title
email: your-email@domain.com
description: You can update the description in update blog details page.

baseurl: "/"
url: http://keralahost.in/beepnride
google_adsense: Your-adsense-code

markdown: kramdown

name: Your awesome title

date: 2019-04-26 11:21:09 +0000
permalink: /:year/:month/:day/:title

logo: false
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: http://keralahost.in/beepnride/
google_analytics: UA-31XXXXXX-X
gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: 
author_image: 

author: beepnride
